services:
  - type: web
    plan: free
    name: restful_payment_gateway_api
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn restful_payment_gateway_api.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PAYSTACK_TEST_SECRET_KEY
        sync: false