###
GET {{base_url}}/payments/m392r2dbbn

###

###
POST {{base_url}}/payments/
Content-Type: application/json

{
    "customer_name": "John Doe",
    "customer_email": "john@example.com",
    "amount": 10.00
}
###
